apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.container.image.name }}:{{ .Values.container.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.container.healthcheck.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.container.healthcheck.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          {{- if .Values.configmap.enabled }}
            - configMapRef:
                name: {{ .Values.name }}
          {{- end }}
          {{- if or .Values.secret.enabled }}
            - secretRef:
                name: {{ .Values.name }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.name }}-volume
              mountPath: /usr/share/nginx/html
              subPath: config.json
              readOnly: true
      volumes:
        - name: {{ .Values.name }}-volume
          configMap:
            name: {{ .Values.name }}
      
      imagePullSecrets:
        - name: regcred
